### ISSUE TITLE
Issue using with multi-entry plugin

### ISSUE THREAD

**Issue by jholt1** [mprt-org/rollup-plugin-incremental#1]
Hey thanks for creating this plugin!

I have tried to get this working in my own repo but have had some issue with getting it to work with the [multi-entry](https://www.npmjs.com/package/@rollup/plugin-multi-entry) plugin.

## Error

Currently, getting the error:

```
'virtual:multi-entry.js' is imported by virtual:multi-entry.js?incremental-entry.js, but could not be resolved – treating it as an external dependency
{
  code: 'ERROR',
  error: Error: 'virtual:multi-entry.js' is imported as an external by virtual:multi-entry.js?incremental-entry.js, but is already an existing non-external module id
```

## Replication

I have created a repo that replicates the issue: https://github.com/jholt1/rollup-incremental-multi

Any ideas on how to get round the problem?

**Comment by Amareis** [comment]
Uh-oh, currently I cannot recommend to use my plugin yet! There is issues with synthetic named exports (so it don't work with commonjs modules) and with exports mangling... But your case I think can be solved, but not just now.

**Comment by jholt1** [comment]
Aha no worries! Was eager to try as it solves the performance issue I am having.

**Comment by Amareis** [comment]
Ok, so I returns to this plugin, managed it to works with SNE and looked at multi-entry. Currently they cannot works in company, since both incremental plugin and multi-entry both change input option. I reflected it in readme and hope in future we found a way to make it better!
