### ISSUE TITLE
Not working with output.file

### ISSUE THREAD

**Issue by cdalexndr** [mprt-org/rollup-plugin-incremental#3]
Getting error:
`You must set "output.dir" instead of "output.file" when using the "output.preserveModules" option.`

**"@mprt/rollup-plugin-incremental": "^0.1.0"
 "rollup": "^2.53.2",**

**Comment by Amareis** [comment]
So, you need to set output.dir option :)

**Comment by cdalexndr** [comment]
Testing with `dir`, now I get:
` Error: UMD and IIFE output formats are not supported for code-splitting builds.`
Does this plugin enable some `code-splitting` option? Without plugin, the build works.

Related: https://github.com/rollup/rollup/issues/2072

**Comment by cdalexndr** [comment]
It seems that the `preserveModules: true` required option is causing this error.

**Comment by Amareis** [comment]
Yep, because of architecture of plugin and rollup itself, it can works only with preserveModules enabled. But it supposed to be used only in development, so you can use ESM for it. See #2
