### ISSUE TITLE
Does it work only in watch mode?

### ISSUE THREAD

**Issue by cdalexndr** [mprt-org/rollup-plugin-incremental#4]
Issuing sequential builds with:
`npx rollup -c rollup.config.dev.js`
I see similar build times, no improvement.

Does it work only in watch mode or is it a configuration issue? 
If yes, readme should be updated to state that watch mode is required.

**Comment by Amareis** [comment]
>readme should be updated to state that watch mode is required

It is :) 
![image](https://user-images.githubusercontent.com/4806617/125765711-25ad3f74-3177-4fbb-9a5d-ffa81f74b22f.png)

**Comment by cdalexndr** [comment]
This note will be more visible if placed below the `rollup -cw` command as a warning.

**Comment by Amareis** [comment]
Done, added note to readme
